name: deploy-aws

on:
  workflow_dispatch:
    branches: [ msa-rms-support ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout rms-generated-client-js
        uses: actions/checkout@v3
        with:
          repository: extact-io/rms-generated-client-js
          path: rms-generated-client-js
      - name: Link rms-generated-client-js
        working-directory: rms-generated-client-js
        run: |
          npm install
          npm link
      - name: Checkout rms-ui-react
        uses: actions/checkout@v3
        with:
          path: rms-ui-react
      - name: Build rms-ui-react
        working-directory: rms-ui-react
        run: |
          yarn install
          npm link @extact-io/rms-generated-client-js
          yarn build
          git show --format='%H' --no-patch > ./build/commit_sha
          echo "commit_sha:`cat ./build/commit_sha`"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-identity-providers-federation-github-actions
          aws-region: ap-northeast-1
      - name: Upload file to S3
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: |
          aws s3 rm s3://$S3_UPLOAD_BUCKET --recursive
          aws s3 cp ./rms-ui-react/build/ s3://$S3_UPLOAD_BUCKET --recursive
      # CloudFrontのキャッシュポリシーをOFFにしてるので都度キャッシュ削除は今のところ不要
      #- name: Delete cache from CloudFront
      #  env:
      #    CLOUD_FRONT_DIST_ID: ${{ secrets.CLOUD_FRONT_DIST_ID }}
      #  run: |
      #    aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_DIST_ID --paths "/*"
