name: deploy-aws

on:
  workflow_dispatch:
    branches: [ msa-rms-support ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout rms-generated-client-js
        uses: actions/checkout@v3
        with:
          path: rms-generated-client-js
      - name: Link rms-generated-client-js
        working-directory: rms-generated-client-js
        run: |
          git clone https://github.com/extact-io/rms-generated-client-js.git
          cd rms-generated-client-js
          npm install
          npm link
          cd ../
          npm link @extact-io/rms-generated-client-js
      - name: Checkout rms-ui-react
        uses: actions/checkout@v3
        with:
          path: rms-ui-react
      - name: Build rms-ui-react
        working-directory: rms-ui-react
        run: |
          yarn install
          npm link @extact-io/rms-generated-client-js
          yarn build
          git show --format='%H' --no-patch > ./build/commit_sha
          echo "commit_sha:`cat ./build/commit_sha`"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Upload file to S3
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: |
          aws s3 rm s3://$S3_UPLOAD_BUCKET --recursive
          aws s3 cp ./build/ s3://$S3_UPLOAD_BUCKET --recursive
